# Generated by Django 5.2.16 on 2026-07-27 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome_usuario", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200, unique=True)),
                (
                    "password",
                    models.CharField(db_column="senha_usuario", max_length=100),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="PerfilDermatologico",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idade", models.IntegerField()),
                (
                    "tipo_pele",
                    models.CharField(
                        choices=[
                            ("oleosa", "Oleosa"),
                            ("seca", "Seca"),
                            ("mista", "Mista"),
                            ("normal", "Normal"),
                        ],
                        max_length=10,
                    ),
                ),
                ("alergias", models.TextField(blank=True, null=True)),
                ("objetivo", models.CharField(max_length=200)),
                (
                    "preferencia_produto",
                    models.CharField(
                        choices=[("creme", "Creme"), ("gel", "Gel")], max_length=10
                    ),
                ),
                ("usa_maquiagem_diariamente", models.CharField(max_length=10)),
                ("foto_rosto", models.CharField(blank=True, max_length=500, null=True)),
                ("dados_ia", models.TextField(blank=True, null=True)),
                ("porcentagem_saude", models.IntegerField()),
                ("fototipo", models.IntegerField(blank=True, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "perfil_dermatologico",
            },
        ),
    ]
