# Generated by Django 5.2.17 on 2026-08-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_perfildermatologico_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=150)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True, null=True)),
                ("url_capa", models.URLField(blank=True, max_length=300, null=True)),
                ("url_leitura", models.URLField(max_length=300)),
            ],
            options={
                "db_table": "artigo",
            },
        ),
        migrations.CreateModel(
            name="Especialista",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("especialidade", models.CharField(max_length=100)),
                ("crm", models.CharField(blank=True, max_length=30, null=True)),
                ("telefone_whatsapp", models.CharField(max_length=20)),
                ("url_foto", models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                "db_table": "especialista",
            },
        ),
    ]
