# Generated by Django 6.0.6 on 2026-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artigo_id_alter_especialista_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildermatologico',
            name='exercicio_frequencia',
            field=models.CharField(choices=[('nunca', 'Nunca ou raramente'), ('1-2x', '1-2x por semana'), ('3-4x', '3-4x por semana'), ('5x+', '5x ou mais por semana')], default='1-2x', max_length=10),
        ),
        migrations.AddField(
            model_name='perfildermatologico',
            name='protetor_solar',
            field=models.IntegerField(choices=[(0, 'Nunca ou raramente'), (1, 'Às vezes'), (2, 'Todos os dias')], default=1),
        ),
        migrations.AddField(
            model_name='perfildermatologico',
            name='sono_horas',
            field=models.CharField(choices=[('curto', '<5h'), ('reduzido', '5-7h'), ('adequado', '7-9h'), ('longo', '>9h')], default='adequado', max_length=10),
        ),
    ]
