# Generated by Django 5.2.17 on 2026-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_artigo_id_alter_especialista_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Limpeza', 'Limpeza'), ('Água Micelar', 'Água Micelar'), ('Tônico', 'Tônico'), ('Sérum', 'Sérum'), ('Hidratante', 'Hidratante'), ('Protetor Solar', 'Protetor Solar'), ('Esfoliante', 'Esfoliante'), ('Máscara Facial', 'Máscara Facial'), ('Óleo Facial', 'Óleo Facial'), ('Contorno de Olhos', 'Contorno de Olhos')], max_length=30)),
                ('tipo_pele', models.CharField(max_length=100)),
                ('preocupacao', models.CharField(max_length=255)),
                ('modo_uso', models.CharField(choices=[('Manhã', 'Manhã'), ('Noite', 'Noite'), ('Manhã e Noite', 'Manhã e Noite')], max_length=20)),
                ('ingrediente_principal', models.CharField(max_length=100)),
                ('fps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tamanho_ml', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('avaliacao', models.DecimalField(decimal_places=1, max_digits=2)),
                ('num_avaliacoes', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_url', models.URLField(blank=True, max_length=300)),
                ('link_produto', models.URLField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.AlterField(
            model_name='artigo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfildermatologico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
