# Generated by Django 5.2.17 on 2026-08-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_alter_artigo_id_alter_especialista_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fonte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='avaliacao',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='num_avaliacoes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
