# Generated by Django 6.0.6 on 2026-09-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfildermatologico_exercicio_frequencia_and_more'),
        ('core', '0006_produto_fonte_alter_produto_avaliacao_and_more'),
    ]

    operations = [
    ]
