"""
Django settings for configuracao project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# carrega o .env local (no Vercel as variaveis vem do painel "Environment Variables")
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-x@$h1x!r(=q&$@z@f25(wtq%p*o3u-(q&$4+0x3$d(a8w6=rjh',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    ".vercel.app",
    "localhost",
    "127.0.0.1",
]

# necessario pros formularios (login, cadastro...) funcionarem em HTTPS no Vercel
CSRF_TRUSTED_ORIGINS = ["https://*.vercel.app"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Adicione o seu app aqui embaixo:
    'core',
]

# usa o nosso Usuario customizado no lugar do User padrao do Django
AUTH_USER_MODEL = 'core.Usuario'

# pra onde o @login_required manda quem nao esta logado (a rota padrao do
# Django, /accounts/login/, nao existe nesse projeto)
LOGIN_URL = 'login'

# credenciais fixas do administrador - usadas na mesma tela de login (email/senha)
# pra liberar o painel /administradores/. nao existe cadastro pra isso, e um
# usuario/senha pre-definidos mesmo
ADMIN_LOGIN_EMAIL = 'admin@lumeskin.com'
ADMIN_LOGIN_SENHA = 'lumeskin2026'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'configuracao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configuracao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Chave da YouCam: coloque YOUCAM_API_KEY no .env.
YOUCAM_API_KEY = os.getenv('YOUCAM_API_KEY', '')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', ''),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'OPTIONS': {'sslmode': 'require'},
    }
}

# bancos MySQL na nuvem (Aiven, TiDB Cloud, etc.) costumam exigir SSL.
# coloque DB_SSL=true nas variaveis de ambiente pra ativar.
# if os.getenv('DB_SSL', '').lower() in ('1', 'true', 'yes'):
#   DATABASES['default']['OPTIONS'] = {'ssl': {'check_hostname': False}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# deixa o WhiteNoise servir o CSS/imagens direto das pastas static dos apps,
# sem precisar rodar collectstatic no Vercel
WHITENOISE_USE_FINDERS = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
